apiVersion: v1
kind: Service
metadata:
  labels:
    app: fetcher
  name: fetcher
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: fetcher
status:
  loadBalancer: {}
