apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: fetcher
  name: fetcher
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: fetcher
    spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              key: AWS_ACCESS_KEY
              name: fetcher-fetcher-env
        - name: AWS_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: AWS_SECRET_KEY
              name: fetcher-fetcher-env
        - name: FACEBOOK_OAUTH_KEY
          valueFrom:
            configMapKeyRef:
              key: FACEBOOK_OAUTH_KEY
              name: fetcher-fetcher-env
        - name: FACEBOOK_URI
          valueFrom:
            configMapKeyRef:
              key: FACEBOOK_URI
              name: fetcher-fetcher-env
        - name: FETCHED_POSTS_TOPIC
          valueFrom:
            configMapKeyRef:
              key: FETCHED_POSTS_TOPIC
              name: fetcher-fetcher-env
        - name: PAGES
          valueFrom:
            configMapKeyRef:
              key: PAGES
              name: fetcher-fetcher-env
        - name: FETCHER_INTERVAL_IN_MINUTES
          valueFrom:
            configMapKeyRef:
              key: FETCHER_INTERVAL_IN_MINUTES
              name: fetcher-fetcher-env
        - name: POSTS_LIMIT
          valueFrom:
            configMapKeyRef:
              key: POSTS_LIMIT
              name: fetcher-fetcher-env
        imagePullPolicy: Always
        image: lk2iosr/fetcher:v2
        name: fetcher
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
