apiVersion: v1
kind: Service
metadata:
  labels:
    app: publisher
  name: publisher
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 5555
    targetPort: 0
  selector:
    app: publisher
status:
  loadBalancer: {}
