apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: publisher
  name: publisher
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
      - image: iosr.facebookapp/publisher:v1
        name: publisher
        resources: {}
      restartPolicy: Always
status: {}
