apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: stats
  name: stats
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: stats
    spec:
      containers:
      - image: iosr.facebookapp/stats:v1
        name: stats
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
