apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: stats
  name: stats
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: stats
    spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              key: AWS_ACCESS_KEY
              name: stats-stats-env
        - name: AWS_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: AWS_SECRET_KEY
              name: stats-stats-env
        - name: AWS_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              key: AWS_QUEUE_NAME
              name: stats-stats-env
        - name: SPRING_USER
          valueFrom:
            configMapKeyRef:
              key: SPRING_USER
              name: stats-stats-env
        - name: SPRING_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: SPRING_PASSWORD
              name: stats-stats-env
        image: lk2iosr/stats:v1
        name: stats
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
